jobs:
  install:
    executor: heroku/default
    steps:
      - heroku/install
  build:
    executor: docker/machine
    steps:
      - checkout
      - run: docker login --username=$DOCKER_LOGIN --password=$DOCKER_PASSWORD registry.heroku.com
      - run: docker build -t registry.heroku.com/mielelle-prod/web .
      - run: docker push registry.heroku.com/mielelle-prod/web
      - run: heroku container:release web -a mielelle-prod

orbs:
  docker: circleci/docker@1.0.1
  heroku: circleci/heroku@1.0.1
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - install
      - build
      