jobs:
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: mielelle-prod/web
      - docker/push:
          image: mielelle-prod/web
          registry: registry.heroku.com
  deploy:
    executor: heroku/default
    steps:
      - heroku/install
      - run: heroku container:login
      - run: heroku container:release web -a mielelle-prod

orbs:
  docker: circleci/docker@1.0.1
  heroku: circleci/heroku@1.0.1
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy
      