jobs:
  install:
    executor: heroku/default
    steps:
      - heroku/install
  build:
    executor: docker/docker
    steps:
      - checkout
      - docker/check:
        registry: registry.heroku.com
      - docker/build:
          image: mielelle-prod/web
      - docker/push:
          image: mielelle-prod/web
          registry: registry.heroku.com
      - run: heroku container:release web -a mielelle-prod

orbs:
  docker: circleci/docker@1.0.1
  heroku: circleci/heroku@1.0.1
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - install
      - build
      